print("Hello World")
print("Kui sooritate ostu, mis on rohkem või võrdne 5000$, saate lisa soodustust!!")
kauba_valik = input("Sisestage kaup, mida soovite osta: ")
kauba_kogus = int(input("Sisestage kauba kogus: "))
asukoht = input("Sisestage State(ut, nv, tx, al, ca): ").upper()